//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicSayAndPlay.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int IDQuery { get; set; }
        public int IDUserInfo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OriginalWorld { get; set; }
        public string TranslatedWorld { get; set; }
        public string ImageUrl { get; set; }
        public int Puntuation { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
